// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PiCommandCenter.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddAgentSessions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AgentSessions",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    Activity = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    AgentName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    Attention = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    CurrentOperation = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    EndedAtUtcTicks = table.Column<long>(type: "INTEGER", nullable: true),
                    LastHeartbeatAtUtcTicks = table.Column<long>(type: "INTEGER", nullable: true),
                    LastSequence = table.Column<long>(type: "INTEGER", nullable: false),
                    Liveness = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    ParentSessionId = table.Column<string>(type: "TEXT", maxLength: 128, nullable: true),
                    ProcessId = table.Column<int>(type: "INTEGER", nullable: true),
                    ProjectId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ProviderSessionId = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    RequestId = table.Column<Guid>(type: "TEXT", nullable: false),
                    Role = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    Runtime = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    RuntimeProfile = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    StartedAtUtcTicks = table.Column<long>(type: "INTEGER", nullable: false),
                    StatusReason = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: false),
                    Version = table.Column<long>(type: "INTEGER", nullable: false),
                    WorkState = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AgentSessions", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AgentSessions_ParentSessionId",
                table: "AgentSessions",
                column: "ParentSessionId");

            migrationBuilder.CreateIndex(
                name: "IX_AgentSessions_RequestId",
                table: "AgentSessions",
                column: "RequestId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AgentSessions");
        }
    }
}
