// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PiCommandCenter.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddNodesRequestsAndEvents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FleetNodes",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    DisplayName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    AgentVersion = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    Status = table.Column<string>(type: "TEXT", maxLength: 16, nullable: false),
                    LastHeartbeatAt = table.Column<long>(type: "INTEGER", nullable: false),
                    CapabilitiesJson = table.Column<string>(type: "TEXT", maxLength: 16384, nullable: false),
                    CreatedAt = table.Column<long>(type: "INTEGER", nullable: false),
                    UpdatedAt = table.Column<long>(type: "INTEGER", nullable: false),
                    Version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FleetNodes", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SessionEvents",
                columns: table => new
                {
                    EventId = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    NodeId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ProjectId = table.Column<Guid>(type: "TEXT", nullable: false),
                    RequestId = table.Column<Guid>(type: "TEXT", nullable: true),
                    SessionId = table.Column<string>(type: "TEXT", maxLength: 128, nullable: true),
                    Sequence = table.Column<long>(type: "INTEGER", nullable: false),
                    Type = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    OccurredAtUtcTicks = table.Column<long>(type: "INTEGER", nullable: false),
                    ReceivedAtUtcTicks = table.Column<long>(type: "INTEGER", nullable: false),
                    PayloadJson = table.Column<string>(type: "TEXT", maxLength: 65536, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SessionEvents", x => x.EventId);
                });

            migrationBuilder.CreateTable(
                name: "RequestClaims",
                columns: table => new
                {
                    RequestId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ProjectId = table.Column<Guid>(type: "TEXT", nullable: false),
                    NodeId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ClaimToken = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    ClaimedAt = table.Column<long>(type: "INTEGER", nullable: false),
                    LeaseExpiresAt = table.Column<long>(type: "INTEGER", nullable: false),
                    Version = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RequestClaims", x => x.RequestId);
                    table.ForeignKey(
                        name: "FK_RequestClaims_WorkRequests_RequestId",
                        column: x => x.RequestId,
                        principalTable: "WorkRequests",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FleetNodes_DisplayName",
                table: "FleetNodes",
                column: "DisplayName");

            migrationBuilder.CreateIndex(
                name: "IX_RequestClaims_ProjectId_LeaseExpiresAt",
                table: "RequestClaims",
                columns: new[] { "ProjectId", "LeaseExpiresAt" });

            migrationBuilder.CreateIndex(
                name: "IX_RequestClaims_RequestId",
                table: "RequestClaims",
                column: "RequestId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SessionEvents_ProjectId_OccurredAtUtcTicks",
                table: "SessionEvents",
                columns: new[] { "ProjectId", "OccurredAtUtcTicks" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FleetNodes");

            migrationBuilder.DropTable(
                name: "RequestClaims");

            migrationBuilder.DropTable(
                name: "SessionEvents");
        }
    }
}
