#!/usr/bin/env bash
# First-time local setup: private data directory plus control-plane --setup
# (admin password hash + 256-bit node token). Never silent insecure defaults.
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

DATA_DIR="${PI_CC_DATA:-${XDG_DATA_HOME:-$HOME/.local/share}/pi-command-center}"
ADMIN_USER="${PI_CC_ADMIN_USERNAME:-admin}"
HASH_FILE="${PI_CC_ADMIN_PASSWORD_FILE:-${DATA_DIR}/admin.password.hash}"
PLAIN_FILE="${PI_CC_ADMIN_PASSWORD_ONCE_FILE:-${DATA_DIR}/admin.password}"
NODE_FILE="${PI_CC_NODE_CREDENTIAL_FILE:-${DATA_DIR}/node.token}"

umask 077
mkdir -p "${DATA_DIR}"
chmod 0700 "${DATA_DIR}"

export Admin__Username="${ADMIN_USER}"
export Admin__PasswordFile="${HASH_FILE}"
export NodeAuthentication__CredentialFile="${NODE_FILE}"
export NodeAuthentication__Header="${NodeAuthentication__Header:-Authorization}"
export NodeAuthentication__Scheme="${NodeAuthentication__Scheme:-Bearer}"

if [[ -f "${HASH_FILE}" && -f "${NODE_FILE}" ]]; then
    chmod 0600 "${HASH_FILE}" "${NODE_FILE}"
    if [[ -f "${PLAIN_FILE}" ]]; then
        chmod 0600 "${PLAIN_FILE}"
    fi
else
    setup_out="$(
        cd "${REPO_ROOT}"
        dotnet run --project src/PiCommandCenter.ControlPlane --no-launch-profile -- --setup
    )"
    password="$(printf '%s\n' "${setup_out}" | sed -n 's/^Password: //p' | head -n1)"
    if [[ -z "${password}" ]]; then
        echo "Control plane --setup did not print a one-time password." >&2
        printf '%s\n' "${setup_out}" >&2
        exit 1
    fi
    umask 077
    printf '%s' "${password}" > "${PLAIN_FILE}"
    chmod 0600 "${HASH_FILE}" "${NODE_FILE}" "${PLAIN_FILE}"
fi

cat > "${DATA_DIR}/local.env" <<EOF
# Generated by scripts/setup-local.sh — source this file; do not commit.
Admin__Username=${ADMIN_USER}
Admin__PasswordFile=${HASH_FILE}
NodeAuthentication__CredentialFile=${NODE_FILE}
NodeAuthentication__Header=${NodeAuthentication__Header}
NodeAuthentication__Scheme=${NodeAuthentication__Scheme}
PI_CC_ADMIN_PASSWORD_ONCE_FILE=${PLAIN_FILE}
EOF
chmod 0600 "${DATA_DIR}/local.env"

PORT="${PI_CC_PORT:-5057}"
BASE_URL="http://127.0.0.1:${PORT}"
INSTALL_ROOT="${PI_CC_INSTALL_ROOT:-${HOME}/.local/lib/pi-command-center}"
APPROVED_ROOT="${PI_CC_APPROVED_ROOT:-$(dirname "${REPO_ROOT}")}"
cat > "${DATA_DIR}/pi-command-center.env" <<EOF
# Generated by scripts/setup-local.sh — loaded by the systemd user units; do not commit.
PI_CC_DATA=${DATA_DIR}
PI_CC_REPO=${REPO_ROOT}
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=${BASE_URL}
Admin__Username=${ADMIN_USER}
Admin__PasswordFile=${HASH_FILE}
NodeAuthentication__CredentialFile=${NODE_FILE}
NodeAuthentication__Header=${NodeAuthentication__Header}
NodeAuthentication__Scheme=${NodeAuthentication__Scheme}
ControlPlane__BaseUrl=${BASE_URL}
ConnectionStrings__ControlPlane=Data Source=${DATA_DIR}/controlplane.db;Cache=Shared
Node__ControlPlaneUrl=${BASE_URL}
Node__EventSpoolPath=${DATA_DIR}/node-spool.db
Projects__ApprovedRoots__0=${APPROVED_ROOT}
Pi__AgentDataDirectory=${DATA_DIR}/pi-agent
Pi__WorkerPath=${INSTALL_ROOT}/runtime/pi-worker/src/index.ts
EOF
chmod 0600 "${DATA_DIR}/pi-command-center.env"

echo "Setup complete."
echo "  data dir:        ${DATA_DIR} (0700)"
echo "  admin user:      ${ADMIN_USER}"
echo "  admin hash:      ${HASH_FILE} (0600)"
echo "  node credential: ${NODE_FILE} (0600)"
echo "  one-time password file (0600): ${PLAIN_FILE}"
echo "  env file:        ${DATA_DIR}/local.env"
echo "  service env:     ${DATA_DIR}/pi-command-center.env"
echo "Repo: ${REPO_ROOT}"
echo "Run scripts/demo.sh next. Do not cat secret files."
